### ISSUE TITLE
Event variables carry no value, yet exporting only works if a changing value is given

### ISSUE THREAD

**Issue by martinhansdk** [SanDisk-Open-Source/pyvcd#14]
When calling `writer.change()` on an event variable, the `value` argument must have a truthy value. This value is ignored when the VCD file is written. In previous versions of pyvcd it was fine to give a constant value such as `1`. This no longer works in 0.1.6 - only the first event gets exported:

```
>>> import sys
>>> from vcd import VCDWriter
>>> with VCDWriter(sys.stdout, timescale='1 ns', date='today') as writer:
...     counter_var = writer.register_var('a.b.c', 'counter', 'event')
...     for timestamp in range(10, 20):
...         writer.change(counter_var, timestamp, 1)
... 
$date today $end
$timescale 1 ns $end
$scope module a $end
$scope module b $end
$scope module c $end
$var event 1 0 counter $end
$upscope $end
$upscope $end
$upscope $end
$enddefinitions $end
#0
$dumpvars
$end
#10
10
>>> 
```

This seems like the wrong behaviour to me because the information an event carries is the timestamp at which it happened, but this information now gets thrown away.

A workaround is to always supply a value that is different from the previous time or give the timestamp as the value argument.

**Comment by jpgrayson** [comment]
Thank you for this report. Agreed that this new behavior is a bug.

I pushed a repair. It would be nice if you (@martinhansdk) could verify the repair for your use case.

**Comment by martinhansdk** [comment]
Thank you for the quick fix. I can confirm that this works for my use case.

pyvcd is awesome, by the way! I'm using it to turn events logged in firmware into waveforms.
