### ISSUE TITLE
Getting syntax error in sample program

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [SanDisk-Open-Source/pyvcd#16]
Hello, I have tried program written in quickstart. Please correct me If I am wrong, it will create vcd file by this given sample program. But in that I am getting syntax. I was trying to figure it out from documentation,  there is no example  for some APIs in that. Following is the code that I am trying to run : 

```
import sys
from vcd import VCDWriter
with VCDWriter(sys.stdout, timescale='1 ns', date='today') as writer:
    counter_var = writer.register_var('a.b.c', 'counter', 'integer', size=8)
    real_var = writer.register_var('a.b.c', 'x', 'real', init=1.23)
    for timestamp, value in enumerate(range(10, 20, 2)):
        writer.change(counter_var, timestamp, value)
        writer.change(real_var, 5, 3.21)

$date today $end
$timescale 1 ns $end
$scope module a $end
$scope module b $end
$scope module c $end
$var integer 8 ! counter $end
$var real 64 " x $end
$upscope $end
$upscope $end
$upscope $end
$enddefinitions $end
#0
$dumpvars
b1010 !
r1.23 "
$end
#1
b1100 !
#2
b1110 !
#3
b10000 !
#4
b10010 !
#5
r3.21 "
```

In this it is giving an error like following: 

![image](https://user-images.githubusercontent.com/29624037/88285902-80f48980-cd0d-11ea-8d9c-6c573f5cac62.png)

So can anyone please help me to solve this? Please let me know if anything needed from myside.

-Shraddha

**Comment by jpgrayson** [comment]
The sample from the README.rst file shows both Python code and the VCD output from running that code. It appears that you are trying to run both the Python code and VCD output with a Python interpreter.

This is the Python code:

```python
>>> import sys
>>> from vcd import VCDWriter
>>> with VCDWriter(sys.stdout, timescale='1 ns', date='today') as writer:
...     counter_var = writer.register_var('a.b.c', 'counter', 'integer', size=8)
...     real_var = writer.register_var('a.b.c', 'x', 'real', init=1.23)
...     for timestamp, value in enumerate(range(10, 20, 2)):
...         writer.change(counter_var, timestamp, value)
...     writer.change(real_var, 5, 3.21)
```

The `>>>` and `...` prefixes are indications that this code could be typed directly into a Python REPL. Remove those prefixes (as it seems you've done) if pasting into a .py file.

This is the VCD output from running the above code. It is obviously not Python code and should be removed from your `pyvcd_ex1.py` file:

```
$date today $end
$timescale 1 ns $end
$scope module a $end
$scope module b $end
$scope module c $end
$var integer 8 ! counter $end
$var real 64 " x $end
$upscope $end
$upscope $end
$upscope $end
$enddefinitions $end
#0
$dumpvars
b1010 !
r1.23 "
$end
#1
b1100 !
#2
b1110 !
#3
b10000 !
#4
b10010 !
#5
r3.21 "
```

Hopefully this clarification helps you get started.
