### ISSUE TITLE
String variable formatting is unsound

### ISSUE THREAD

**Issue by whitequark** [SanDisk-Open-Source/pyvcd#17]
String formatting checks (if `check` is true) for spaces (ASCII 0x20), but not for other special characters, some of which lead to even worse results:
```
>>> from vcd import VCDWriter
>>> writer = VCDWriter(open("foo.vcd", "wt"))
>>> var = writer.register_var(scope="", name="test", var_type="string")
>>> writer.change(var,0,"a\nb")
>>> writer.close()
```

As far as I know, the grammar accepted for string values is not documented, but [this mailing list post](https://sourceforge.net/p/gtkwave/mailman/message/30307152/) indicates that spaces "and such" may be escaped as hex or octal escapes, and [this function in gtkwave](https://github.com/gtkwave/gtkwave/blob/master/gtkwave3/src/vcd.c#L610-L644) indicates that the complete list of characters implied in "and such" would be `\x20`, `\r`, `\n`, `\t`, and of course `\\`.

```
>>> writer = VCDWriter(open("foo.vcd", "wt"))
>>> var = writer.register_var(scope="", name="test", var_type="string")
>>> writer.change(var,0,r"a\x09b\x20c")
>>> writer.close()
```
![Screenshot_20201206_021617](https://user-images.githubusercontent.com/54771/101269647-06328500-3769-11eb-9994-00f0decce9ad.png)

At least, pyvcd should check for more than just spaces when emitting strings. However, I would strongly prefer if it actually escaped the string appropriately, since it should not be the responsibility of downstream projects to hunt down such obscure, barely documented detail.

Let me know if you'd like me to implement this.

**Comment by jpgrayson** [comment]
Thanks for this issue report @whitequark. And thanks for bravely digging into the GTKWave code.

I agree that pyvcd should encode string values. I believe this could/should happen in `StringVariable.format_value()`. I think we can do the required encoding with `str.translate()`.

I'd be happy to have you take on this change.

**Comment by whitequark** [comment]
Can you do a release? I'd like to remove some hacks from nMigen related to string formatting.
