### ISSUE TITLE
Sample code doesn't execute.

### ISSUE THREAD

**Issue by rdburns** [SanDisk-Open-Source/pyvcd#4]
I am trying to execute the sample code in the readme and I get an 

*** AttributeError: 'str' object has no attribute 'write'

I am running Python 2.7 in Ubuntu.

**Comment by rdburns** [comment]
Oops, my mistake.

**Comment by jpgrayson** [comment]
Glad you're taking a look at pyvcd. Don't hesitate to post any other issues you run into.
